name: Test Pipeline

on:
  push:
    branches:
      - main
      - '**' 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API in Background
        run: |
          nohup python src/main.py & 
          for i in {1..10}; do
            if curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8000/health; then
              break
            fi
            sleep 5
          done || exit 1

      - name: Run Tests
        env:
          API_URL: "http://localhost:8000" 
        run: |
          pytest --html=report.html --self-contained-html --cov=./ --cov-report=html --log-cli-level=INFO --log-file=logfile.log --log-file-level=DEBUG

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logfile
          path: logfile.log

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./htmlcov
